#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker369"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "37dd0cc163364315923866ce6a6648c6" }
]

[assets]
directory = "./public"
